name: Update GitHub Stats SVG

on:
  schedule:
    - cron: '0 0 * * *' # Her gece 00:00'da otomatik çalışır
  push:
    branches: [ main ] # Main branch'ine her kod attığında çalışır
  workflow_dispatch: # Manuel çalıştırma butonunu aktif eder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests lxml python-dateutil

      - name: Run script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Kasadaki şifreyi buraya güvenle çeker
          USER_NAME: "alperersy" # Kullanıcı adını buraya yazabilirsin
        run: python today.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update stats SVG" || echo "No changes to commit"
          git push